import React, { ReactElement } from "react";

interface Props {}

export default function Head({}: Props): ReactElement {
  return (
    <Head>
      <title>Watch store</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
